# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-30 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classifer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='keywords',
            name='keywords',
        ),
        migrations.AddField(
            model_name='keywords',
            name='keywords',
            field=models.ManyToManyField(to='Classifer.KeywordList'),
        ),
    ]
