# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-30 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classifer', '0004_auto_20160130_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='college',
            field=models.CharField(default='NITW', max_length=300),
        ),
        migrations.AddField(
            model_name='article',
            name='relevant',
            field=models.BooleanField(default=True),
        ),
    ]
