# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-31 03:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Classifer', '0005_auto_20160130_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='addedat',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 1, 31, 3, 12, 14, 844607, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
